version: "3.9"
services:
  inspector:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    environment:
      HOST: "0.0.0.0"
    ports:
      - "6274:6274" # UI
      - "6277:6277" # proxy
    depends_on:
      - vulners-mcp
  vulners-mcp:
    image: vulners-mcp:latest
    environment:
      MCP_TRANSPORT_MODE: "http"
      VULNERS_BASE_URL: "https://vulners.com"
      VULNERS_API_KEY: "${VULNERS_API_KEY}"
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'

            import socket,sys; s=socket.socket(); s.settimeout(1); s.connect(('localhost',8000)); s.close(); sys.exit(0)

            PY"
        ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
